title: Robertus Dwi Ari Utomo
logo: "/images/ari.jpg?raw=true"
favicon: /images/favicon.png
description:
  <br>
  Student at <b>Faculty of Computer Science, Brawijaya's University </b>
  <br> <br>
  <a href = "https://globalgamejam.org/users/corta55"> Global Game Jam Profile </a>

theme: jekyll-theme-minimal
minimal_mistakes_skin: "dark"
