title: Robertus Dwi Ari Utomo
logo: "/images/ari.jpg?raw=true"
description:
  <br> <br>
  Student at <b>Faculty of Computer Science, Brawijaya's University </b>
  <br> <br>
  Head of Programmer Division at <b>Raion Community</b>
  <br> <br>

theme: jekyll-theme-minimal