title: Robertus Dwi Ari Utomo
logo: "/images/ari.jpg?raw=true"
description:
  <br>
  Student at <b>Faculty of Computer Science, Brawijaya's University </b>
  <br>
  Head of Programmer Division at <b>Raion Community</b>
  <br>

  <a href = "https://globalgamejam.org/users/corta55"> Global Game Jam Profile </a>

theme: jekyll-theme-minimal
