title: Robertus Dwi Ari Utomo
logo: "/images/ari.png?raw=true"
description:
  <br>
  Mahasiswa <b>Fakultas Ilmu Komputer, Universitas Brawijaya </b>
  <br> <br>
  <a href = "https://globalgamejam.org/users/corta55"> Global Game Jam Profile </a>

theme: jekyll-theme-minimal

