title: Robertus Dwi Ari Utomo
logo: "/images/ari.png?raw=true"
description:
  <br>
  Saya seorang <b> Game Programmer </b> dengan pengalaman menggunakan Unity sejak Januari 2018.
  <br> <br>
  <a href = "https://globalgamejam.org/users/corta55"> Global Game Jam Profile </a>

theme: jekyll-theme-minimal

