title: Robertus Dwi Ari Utomo
logo: "/images/ari.jpg?raw=true"
description:

  Student at <b>Faculty of Computer Science, Brawijaya's University </b>

  <a href = "https://globalgamejam.org/users/corta55"> Global Game Jam Profile </a>

theme: jekyll-theme-minimal
