title: Robertus Dwi Ari Utomo
logo: "/images/ari.png?raw=true"
description:
  <br>
  Student at <b>Faculty of Computer Science, Brawijaya's University </b>
  <br> <br>
  <a href = "https://globalgamejam.org/users/corta55"> Global Game Jam Profile </a>

theme: jekyll-theme-minimal

