title: Robertus Dwi Ari Utomo
logo: "/images/ari.jpg?raw=true"
description:
  <br> <br>
  Student at Faculty of Computer Science, Brawijaya's University
  <br> <br>
  Head of Programmer Division at Raion Community
  <br> <br>

theme: jekyll-theme-minimal